package com.intensity.caixinha.entity;

public enum BoxType {
	SAIDAS_COM_AMIGOS,
	SAIDAS_EM_CASAL,
	VIAGENS_EM_CASAL,
	INTIMO_EM_CASAL,
	VIAGENS_COM_AMIGOS,
	EXPERIENCIAS_COM_AMIGOS,
	SAIR_DA_ROTINA,
	PRIMEIRAS_VEZES,
	DESCONFORTO_LEVE,
	MOMENTOS_DE_CONEXAO,
	EXPERIENCIAS_DIFERENTES
}
